### ISSUE TITLE
Tables are not readable

### ISSUE THREAD

**Issue by rugk** [Kirschn/Tellschn#6]
![github](https://user-images.githubusercontent.com/11966684/76557737-61ff0480-649c-11ea-9c70-8bf45fa3b0d8.png)

**Comment by rflrkn** [comment]
Whoops. Light and dark styles got mixed up there. I’ll fix that tomorrow.

**Comment by rugk** [comment]
Also done a PR for you :wink:

**Comment by rflrkn** [comment]
Will check that tomorrow, thanks!
