### ISSUE TITLE
Light and dark styles

### ISSUE THREAD

**Issue by rugk** [Kirschn/Tellschn#8]
Inhttps://github.com/Kirschn/Tellschn/issues/6#issuecomment-598366178 it was said there is a dark style?
Huh, I did not see that anywhere in the GUI or so.

Also remember there is a built-in way for websites to detect what style the user wants:

### Pitch

There is a quite new CSS media query feature called [`prefers-color-scheme`](https://developer.mozilla.org/docs/Web/CSS/@media/prefers-color-scheme). It allows you to detect whether the system/user wants a dark website, so you can adjust your CSS.

Currently it is only supported by Safari and Firefox 67 or higher.

Anyway, it would be great, if you could make use of this. As you already have a dark mode, just (when the user did not override it) maybe automatically switch to the one the browser requests.

BTW: I also have [a Firefox add-on called “Dark Mode Website Switcher”](https://addons.mozilla.org/firefox/addon/dark-mode-website-switcher/?src=external-github-issue) ([source code](https://github.com/rugk/website-dark-mode-switcher))  that you can use to toggle this setting in Firefox directly – without needing to change the system option. Maybe that could be helpful.

### Related

Same Media Queries Level 5 CSS spec introduced these media queries: https://github.com/tootsuite/mastodon/issues/10975

**Comment by rflrkn** [comment]
Huh? Tellschn actually uses prefers-color-scheme.

**Comment by rugk** [comment]
Uhm, oaky, did not have such a deep look at the source code sorry :laughing:
